services:
  a1_assignment:
    image: a1_assignment:prod
    container_name: a1
    environment:
      - WEIGHTS=/models/car_price.model
    volumes:
      - ${PWD}/models/:/app/weights
    stdin_open: true        # Enables interactive mode
    tty: true  
