version: '3.8'

services:
  a1_assignment:
    # image: a1_assignment:prod
    image: koala007/a1_assignment:prod
    container_name: a1
    build: 
      context: ..
      dockerfile: docker/Dockerfile
      target: prod
    # environment:
    #   - WEIGHTS=/models/car_price.model
    # volumes:
    #   - ./models:/app/weights  
    ports:
      - "8000:8000"  
    stdin_open: true        
    tty: true