name: Test CI Workflow

on:
  push:
    paths:
      - '.github/workflows/test.yml'
      - 'A1_KaungHtetCho/**'
  pull_request:
    paths:
      - '.github/workflows/test.yml'
      - 'A1_KaungHtetCho/**'

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Print a Message
        run: echo "GitHub Actions is working correctly!"

      - name: List Files in A1_KaungHtetCho Folder
        run: ls -al A1_KaungHtetCho
